name: get_paper_yaml

on:   
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     token: ${{secrets.GITHUB_TOKEN}}
     repo: ${{github.repository}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run python
      run: |
          python3 -m pip install pyyaml 
          python get_paper.py
    - name: CSV commit
      run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USER_NAME}}
          git add data/paper_database.csv
          git commit -m "add csv"
          git push origin main